### ISSUE TITLE
Add options not to store $source if I want just to store and search object

### ISSUE THREAD

**Issue by xumix** [rokeller/Lucene.Net.ObjectMapping#3]
subj
whis will reduce index size dramatically

**Comment by rokeller** [comment]
Thanks. I like the idea, but just to verify: Unless the $source is stored, you will not be able to get an object back (from this library) for the documents that are found through a query. Is that really what you want?

**Comment by xumix** [comment]
Yep, I'll just need some of the props, or just Id's

**Comment by rokeller** [comment]
This has been addressed with 937eba100562ee8e6cc416486df1e7f3a57b4d81.
The changes will be added to the NuGet package with the next release (no ETA yet).

**Note**: Since the default (and only built-in) Object Mapper (`JsonObjectMapper`) does **not** store any of the mapped fields, you will need to **use your own Object Mapper** for now. I have however started working on addressing this issue too, by designing a new Object Mapper that can be used to also store (instead of just indexing) fields per your own business logic or declarations (attributes).

**Note 2**: As it stands today, you also won't be able to use the built-in LINQ provider to query for objects iff you don't store the source. To address this, I have started working on adding support for the `Cast<T>()` method on `IQueryable` to allow casting a query to an `IQueryable<Document>` so you can work with the documents directly.
