### ISSUE TITLE
Filteres Search Don't work

### ISSUE THREAD

**Issue by Humbledonk** [rokeller/Lucene.Net.ObjectMapping#4]
I've rebuilt my index using your object mapping library however I had a BooleanFilter when I searched on my previous index that doesn't work anymore since the rebuild, any idea why?

**Comment by rokeller** [comment]
I will need more information than what you have presented: how did you
create the index, and what was the name of the field when you indexed it?
What does your object and your query look like? Do you have sample code?

I suspect that your BooleanFilter works with the wrong field name, but
unless I get more information, it's all just guessing.

**Comment by Humbledonk** [comment]
Yeah I understand that, sorry for the lack of information. Before I go posting more code maybe this could answer the question, not sure though.

This is how the field was indexed before: 
doc.Add(new Field("ProductId", urlModel.ProductId.ToString(), Field.Store.YES, Field.Index.NOT_ANALYZED));

does this differ from how it is indexed now and if so, could this cause the filter to not have any effect?

This is the filter and search below:

`//Create filter.
var filter = new TermsFilter();

//Add term.
//filter.AddTerm(new Term("ProductId", Convert.ToString(productId)));

//Construct boolean filter.
BooleanFilter  filter = new BooleanFilter();

//Add supplied filter.
filter.Add(new FilterClause(termsFilter, Occur.MUST));

```
        // set up lucene searcher
        using (var searcher = new IndexSearcher(LuceneUtil.OpenLuceneIndex(_luceneDir), false))
        {   
            //Construct analyzer.
            var analyzer = new StandardAnalyzer(Version.LUCENE_30);

            // search by single field
            if (!string.IsNullOrEmpty(searchField))
            {
                //Construct query parser.
                var parser = new QueryParser(Version.LUCENE_30, searchField, analyzer);

                //Parse query. 
                var query = LuceneUtil.ParseQuery(searchQuery, parser);

                //Perform search.
                var hits = searcher.Search(query, filter, hits_limit, Sort.RELEVANCE).ScoreDocs;

                //var hits = searcher.Search<UrlModel>(query, 100).ScoreDocs;

                //Map Lucene documents to entities.
                var results = _mapLuceneToDataList(hits, searcher);

                //Close handle.
                analyzer.Close();

                //Dispose handle.
                searcher.Dispose();

                //Return results.
                return results;
            }`
```

**Comment by Humbledonk** [comment]
Actually it was wrong to say the filter doesn't have any effect because I simply don't get any results when applying the filter.

**Comment by Humbledonk** [comment]
Can you see anything from that or still not enough info?

Thanks

**Comment by rokeller** [comment]
One question: What's the type of your property 'ProductId'? For integer
values, the object mapping lib maps those to long values in the Lucene
indices, and as a result the filters and queries must be built that way too.

Also, I'm not sure about this: did you create the index with the object
mapping lib, or with your own code? v1.x of the object mapping lib requires
a very specific structure in the indices, including the serialized JSON of
the object, or otherwise the searching and deserialization/mapping back to
objects won't work. In other words: the mapping lib doesn't know your
custom way of storing data in the index, and therefore likely won't be
useful with indices not created/managed with the object mapping lib.

**Comment by Humbledonk** [comment]
Q1: Yes the ProductId is an integer.

I've created the index with the latest version of the object mapping lib and everything works, including deserialization/mapping back to objects. It's just the filter part I couldn't get to work.

Thanks

**Comment by rokeller** [comment]
Thanks for the info. I think since the integers are stored/indexed as
integers (and not strings), you cannot search for the product ID by the
string representation as such, you first need to create a representation of
the ID that is understood by Lucene.Net. IMO, either one of the following
two should do the trick:

filter.AddTerm(new Term("ProductId",
NumericUtils.IntToPrefixCoded(productId)));
// or
filter.AddTerm(new Term("ProductId",
NumericUtils.LongToPrefixCoded(productId)));

This way, the filter is updated with the term as it is stored in the actual
index, and then you should find the corresponding item.

Let me know if you need more info.

**Comment by Humbledonk** [comment]
I could not get it to work with that code unfortunately so instead I added a string version of productId to index and now the filtering works.

**Comment by Humbledonk** [comment]
I have another question, not sure if I should post it here but I guess I can remove it otherwise. Is there a way to mark a property not to be indexed?

**Comment by rokeller** [comment]
Using the default settings when you create the documents through the mapping lib, all properties that are JSON serialized are also indexed. You can however write your own `IObjectMapper` and use non-default `MappingSettings` to have full control over which fields are indexed and which aren't.

**Comment by Humbledonk** [comment]
Ok great!, I'll look into that. 

Thanks a bunch for your help and it seems to work now.

I tried the NumericUtils code again in the filter and it actually does work, don't know why I could not get it to work at first. Below is the one that worked for me and productId is an Integer:
`filter.AddTerm(new Term("ProductId", Lucene.Net.Util.NumericUtils.LongToPrefixCoded(productId)));`

Thanks man!
